# 【問題1】行列積を手計算する
## AとBの行列積を手計算で解いてください。計算過程もマークダウンテキストを用いて説明してください。

In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print('A :{}'.format(a_ndarray))
print('B :{}'.format(b_ndarray))

A :[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
B :[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


## 計算後の行列をCとすると
### C(1, 1)=A(1, 1) * B(1, 1) + A(1, 2) * B(2, 1) + A(1, 3) * B(3, 1) =6
### C(1, 2)=A(1, 1) * B(1, 2) + A(1, 2) * B(2, 2) + A(1, 3) * B(3, 2) =29
### C(1, 3)=A(1, 1) * B(1, 3) + A(1, 3) * B(2, 3) + A(1, 3) * B(3, 3) =-20
### C(2, 1)=A(2, 1) * B(1, 1) + A(2, 2) * B(2, 1) + A(2, 3) * B(3, 1) =12
### C(2, 2)=A(2, 1) * B(1, 2) + A(2, 2) * B(2, 2) + A(2, 3) * B(3, 2) =52
### C(2, 3)=A(2, 1) * B(2, 3) + A(2, 3) * B(2, 3) + A(2, 3) * B(3, 3) =38
### C(3, 1)=A(3, 1) * B(1, 1) + A(3, 2) * B(2, 1) + A(3, 3) * B(3, 1) =-18
### C(3, 2)=A(3, 1) * B(3, 2) + A(3, 2) * B(3, 2) + A(3, 3) * B(3, 2) =-51
### C(3, 3)=A(3, 1) * B(3, 3) + A(3, 3) * B(2, 3) + A(3, 3) * B(3, 3) =-48

# 【問題2】NumPyの関数による計算

In [2]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題3】ある要素の計算を実装

In [5]:
calculate_matrix = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        for k in range(3):
            calculate_matrix[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
calculate_matrix

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

# 【問題4】行列積を行う関数の作成

In [6]:
def matrix_multiplication(a_ndarray, b_ndarray):
    calculate_matrix = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))
    for i in range(a_ndarray.shape[0]):
        for j in range(b_ndarray.shape[1]):
            for k in range(a_ndarray.shape[1]):
                calculate_matrix[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
    return calculate_matrix

In [7]:
matrix_multiplication(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [8]:
f_ndarray = np.array([[-1, 2], [4, -5], [7, 8]])
g_ndarray = np.array([[0, 2, 1], [0, 2, -8]])

In [9]:
matrix_multiplication(f_ndarray, g_ndarray)

array([[  0.,   2., -17.],
       [  0.,  -2.,  44.],
       [  0.,  30., -57.]])

In [10]:
np.matmul(f_ndarray, g_ndarray)

array([[  0,   2, -17],
       [  0,  -2,  44],
       [  0,  30, -57]])

# 【問題5】計算が定義されない入力を判定する

In [11]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [13]:
matrix_multiplication(d_ndarray, e_ndarray)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [14]:
def modified_matrix_multiplication(a_ndarray, b_ndarray):
    if a_ndarray.shape[0] == b_ndarray.shape[1]:
        calculate_matrix = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))
        for i in range(a_ndarray.shape[0]):
            for j in range(b_ndarray.shape[1]):
                for k in range(a_ndarray.shape[1]):
                    calculate_matrix[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
        return calculate_matrix
    else:
        print("""
        第一引数の列数と第二引数の行数が異なります。
        Aの列数: {}
        Bの行数: {}
        """.format(a_ndarray.shape[0], b_ndarray.shape[1]))

In [15]:
modified_matrix_multiplication(d_ndarray, e_ndarray)


        第一引数の列数と第二引数の行数が異なります。
        Aの列数: 2
        Bの行数: 3
        


In [16]:
def modified_matrix_multiplication_2(a_ndarray, b_ndarray):
    if a_ndarray.shape[0] != b_ndarray.shape[1]:
        raise IndexError("""
        第一引数の列数と第二引数の行数が異なります。
        Aの列数: {}
        Bの行数: {}
        """.format(a_ndarray.shape[0], b_ndarray.shape[1]))
    else:
        calculate_matrix = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))
        for i in range(a_ndarray.shape[0]):
            for j in range(b_ndarray.shape[1]):
                for k in range(a_ndarray.shape[1]):
                    calculate_matrix[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
        return calculate_matrix

In [18]:
modified_matrix_multiplication_2(d_ndarray, e_ndarray)

IndexError: 
        第一引数の列数と第二引数の行数が異なります。
        Aの列数: 2
        Bの行数: 3
        

In [19]:
modified_matrix_multiplication(d_ndarray, e_ndarray.T)

array([[ 46.,  -4.],
       [-34.,  73.]])

In [20]:
modified_matrix_multiplication(d_ndarray, np.transpose(e_ndarray))

array([[ 46.,  -4.],
       [-34.,  73.]])