In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# 【問題1】これまで利用してきたクラスの列挙

## panadas:DataFrame
## matplotlib:Figure
## scikit-learn:StandardScalar, LinearRegression, RandomForestClassifier

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

## メソッド：sum(), append(), int(), split(), format(), replace(), concat()
## インスタンス変数：shape, mean_, var_, coef_, intercept_

#  【問題3】標準化クラスをスクラッチで作成

In [2]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特徴量
        """
        X_scaled = (X-self.mean_)/np.sqrt(self.var_)
        return X_scaled

In [3]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# 【問題4】 四則演算を行うクラスの作成

In [4]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if type(value) == int or type(value) == float:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            print('数値を引数に入力してください。')
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        if type(value2) == int or type(value2) == float:
            self.value += value2
            print(self.value)
        else:
            print('数値を引数に入力してください。')
    def minus(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        if type(value3) == int or type(value3) == float:
            self.value -= value3
            print(self.value)
        else:
            print('数値を引数に入力してください。')
    def multiply(self, value4):
        """
        受け取った引数をself.valueにかける
        """
        if type(value4) == int or type(value4) == float:
            self.value *= value4
            print(self.value)
        else:
            print('数値を引数に入力してください。')
    def divide(self, value5):
        """
        受け取った引数でself.valueを割る
        """
        if type(value5) == int or type(value5) == float:
            self.value /= value5
            print(self.value)
        else:
            print('数値を引数に入力してください。')
        
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.minus(2)
print("value : {}".format(example.value))
example.multiply(4)
print("value : {}".format(example.value))
example.divide(6)
print("value : {}".format(example.value))
example_2 = ExampleClass('dive')

初期値5が設定されました
value : 5
8
value : 8
6
value : 6
24
value : 24
4.0
value : 4.0
数値を引数に入力してください。
